version: '3.6'
services:
  #================================= DEVELOPMENT =============================================
  app-dev:
    container_name: app-dev
    build:
      context: .
      target: development
    depends_on:
      - 'postgres'
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    environment:
      POSTGRES_CONNECTION_STRING: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
    volumes:
      - ./:/app/
      - /app/node_modules
    networks:
      - network
  #================================= TEST =============================================
  app-test:
    container_name: app-test
    build:
      context: .
      target: test
    command: sh -c './docker-scripts/wait-for postgres:${POSTGRES_PORT} -- npm test'
    depends_on:
      - 'postgres'
    ports:
      - '8040:8040'
    env_file:
      - ./.env
    environment:
      POSTGRES_CONNECTION_STRING: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      NODE_ENV: test
    volumes:
      - ./:/app/
      - /app/node_modules
    networks:
      - network
  #================================= PRODUCTION =============================================
  app-prod:
    container_name: app-prod
    build:
      context: .
      target: production
    command: sh -c './docker-scripts/wait-for postgres:${POSTGRES_PORT} -- npm start'
    depends_on:
      - 'postgres'
    ports:
      - '8080:8080'
    env_file:
      - ./.env
    environment:
      POSTGRES_CONNECTION_STRING: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      NODE_ENV: production
    networks:
      - network
  #================================= POSTGRES DB =============================================
  postgres:
    container_name: pg_container
    image: postgres:14.5-alpine
    restart: always
    env_file:
      - ./.env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      # When the PostgreSQL container is started it will run any scripts
      # provided in the `docker-entrypoint-initdb.d` directory, this connects
      # our seed file to that directory so that it gets run
      - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
    networks:
      - network

networks:
  network:
    driver: bridge
    name: ninja_network
